version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/" # Raíz del proyecto
    schedule:
      interval: "weekly"

  # Agrega más módulos según tus subdirectorios
  - package-ecosystem: "gradle"
    directory: "/app" # Suponiendo que tienes un subproyecto en app/
    schedule:
      interval: "weekly"

  # Agrega más módulos según tus subdirectorios
  - package-ecosystem: "gradle"
    directory: "/shared" # Suponiendo que tienes un subproyecto en app/
    schedule:
      interval: "weekly"

  # Agrega más módulos según tus subdirectorios
  - package-ecosystem: "gradle"
    directory: "/build-logic" # Suponiendo que tienes un subproyecto en app/
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "gradle"
    directory: "/feature/apps-picker/api" # Suponiendo que tienes un subproyecto en app/
    schedule:
      interval: "weekly"

  # Agrega más módulos según tus subdirectorios
  - package-ecosystem: "gradle"
    directory: "/feature/apps-picker/impl" # Suponiendo que tienes un subproyecto en app/
    schedule:
      interval: "weekly"
      
  # Agrega más módulos según tus subdirectorios
  - package-ecosystem: "gradle"
    directory: "/feature/crashes/api" # Suponiendo que tienes un subproyecto en app/
    schedule:
      interval: "weekly"

  # Agrega más módulos según tus subdirectorios
  - package-ecosystem: "gradle"
    directory: "/feature/crashes/apps-list" # Suponiendo que tienes un subproyecto en app/
    schedule:
      interval: "weekly"

  # Agrega más módulos según tus subdirectorios
  - package-ecosystem: "gradle"
    directory: "/feature/crashes/common" # Suponiendo que tienes un subproyecto en app/
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "gradle"
    directory: "/feature/crashes/details" # Suponiendo que tienes un subproyecto en app/
    schedule:
      interval: "weekly"

  # Agrega más módulos según tus subdirectorios
  - package-ecosystem: "gradle"
    directory: "/feature/crashes/impl" # Suponiendo que tienes un subproyecto en app/
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/feature/crashes/list" # Raíz del proyecto
    schedule:
      interval: "weekly"

  # Agrega más módulos según tus subdirectorios
  - package-ecosystem: "gradle"
    directory: "/feature/filters/api" # Suponiendo que tienes un subproyecto en app/
    schedule:
      interval: "weekly"

  # Agrega más módulos según tus subdirectorios
  - package-ecosystem: "gradle"
    directory: "/feature/filters/edit" # Suponiendo que tienes un subproyecto en app/
    schedule:
      interval: "weekly"

  # Agrega más módulos según tus subdirectorios
  - package-ecosystem: "gradle"
    directory: "/feature/filters/impl" # Suponiendo que tienes un subproyecto en app/
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "gradle"
    directory: "/feature/filters/list" # Suponiendo que tienes un subproyecto en app/
    schedule:
      interval: "weekly"

  # Agrega más módulos según tus subdirectorios
  - package-ecosystem: "gradle"
    directory: "/feature/logging/api" # Suponiendo que tienes un subproyecto en app/
    schedule:
      interval: "weekly"
      
  # Agrega más módulos según tus subdirectorios
  - package-ecosystem: "gradle"
    directory: 
        - "/feature/logging/extended-copy"
        - "/feature/logging/impl"
        - "/feature/logging/list"
        - "/feature/logging/search"
        - "/feature/logging/service"
        - "/feature/recordings/api"
        - "/feature/recordings/details"
        - "/feature/recordings/impl"
        - "/feature/recordings/list"
        - "/feature/settings"
        - "/feature/setup"
        - "/build-logic/convention"
        - "/core/arch"
        - "/core/database"
        - "/core/datetime"
        - "/core/navigation"
        - "/core/preferences"
        - "/core/terminals"
        - "/core/ui-compose"
        - "/core/tests"
        - "/core/ui"
    schedule:
      interval: "weekly"
