version: 2

updates:
  - package-ecosystem: "gradle"
    directories: 
      - "/"
      - "/app"
      - "/shared"
      - "/build-logic"
      - "/feature/apps-picker/api"
      - "/feature/apps-picker/impl"
      - "/feature/crashes/api"
      - "/feature/crashes/apps-list"
      - "/feature/crashes/common"
      - "/feature/crashes/details"
      - "/feature/crashes/impl"
      - "/feature/crashes/list"
      - "/feature/filters/api"
      - "/feature/filters/edit"
      - "/feature/filters/impl"
      - "/feature/filters/list"
      - "/feature/logging/api"
      - "/feature/logging/extended-copy"
      - "/feature/logging/impl"
      - "/feature/logging/list"
      - "/feature/logging/search"
      - "/feature/logging/service"
      - "/feature/recordings/api"
      - "/feature/recordings/details"
      - "/feature/recordings/impl"
      - "/feature/recordings/list"
      - "/feature/settings"
      - "/feature/setup"
      - "/build-logic/convention"
      - "/core/arch"
      - "/core/database"
      - "/core/datetime"
      - "/core/navigation"
      - "/core/preferences"
      - "/core/terminals"
      - "/core/ui-compose"
      - "/core/tests"
      - "/core/ui"
    registries: "*"
    schedule:
      interval: "daily"
    groups:
      kotlin-ksp:
        patterns:
          - "org.jetbrains.kotlin:*"
          - "org.jetbrains.kotlin.*"
          - "com.google.devtools.ksp"
          - "org.gradle.*"
          - "com.android.*"
          - "androidx.*"

registries:
  maven-google:
    type: "maven-repository"
    url: "https://maven.google.com"
    replaces-base: true
