version: 2

updates:
  - package-ecosystem: "gradle"
    directories: 
      - "/"
      - "/app"
      - "/shared"
      - "/build-logic"
      - "/feature/apps-picker/api"
      - "/feature/apps-picker/impl"
      - "/feature/crashes/api"
      - "/feature/crashes/apps-list"
      - "/feature/crashes/common"
      - "/feature/crashes/details"
      - "/feature/crashes/impl"
      - "/feature/crashes/list"
      - "/feature/filters/api"
      - "/feature/filters/edit"
      - "/feature/filters/impl"
      - "/feature/filters/list"
      - "/feature/logging/api"
      - "/feature/logging/extended-copy"
      - "/feature/logging/impl"
      - "/feature/logging/list"
      - "/feature/logging/search"
      - "/feature/logging/service"
      - "/feature/recordings/api"
      - "/feature/recordings/details"
      - "/feature/recordings/impl"
      - "/feature/recordings/list"
      - "/feature/settings"
      - "/feature/setup"
      - "/build-logic/convention"
      - "/core/arch"
      - "/core/database"
      - "/core/datetime"
      - "/core/navigation"
      - "/core/preferences"
      - "/core/terminals"
      - "/core/ui-compose"
      - "/core/tests"
      - "/core/ui"
    registries: "*"
    schedule:
      interval: "daily"
    groups:
      kotlin-ksp:
        patterns:
          - "org.jetbrains.kotlin:*"
          - "org.jetbrains.kotlin.*"
          - "org.jetbrains.compose.*"
          - "org.jetbrains.exposed.*"
          - "org.gradle.*"
          - "androidx.*"
          - "com.android.*"
          - "com.google.*"
          - "com.google.devtools.ksp"
          - "com.google.dagger.*"
          - "com.google.firebase.*"
          - "com.google.accompanist:*"
          - "com.squareup.*"
          - "com.squareup.retrofit2.*"
          - "com.squareup.okhttp3.*"
          - "com.squareup.moshi.*"
          - "com.github.*"
          - "io.coil-kt:*"
          - "io.ktor.*"
          - "org.koin.*"
          - "org.jetbrains.kotlinx.*"
          - "io.insert-koin.*"
          - "org.apache.*"
          - "org.slf4j.*"

registries:
  maven-google:
    type: "maven-repository"
    url: "https://maven.google.com"
    replaces-base: true

  maven-central:
    type: "maven-repository"
    url: "https://repo.maven.apache.org/maven2"

  jitpack:
    type: "maven-repository"
    url: "https://jitpack.io"

  gradle-plugin-portal:
    type: "maven-repository"
    url: "https://plugins.gradle.org/m2/"

  kotlin-jetbrains:
    type: "maven-repository"
    url: "https://maven.pkg.jetbrains.space/kotlin/p/kotlin/dev"
    
